# projections-map.R
#
# Exports the Native land boundaries used by the web map in docs/ as
# simplified GeoJSON plus a small search index. The page itself
# (docs/index.html, docs/app.js, docs/app.css) is hand-written against the
# Montana Climate Office web style kit (mt-climate-office/mco-web-style) and is
# NOT generated by this script.
#
# Inputs:  native-land.parquet (built by projections.R)
# Outputs: docs/data/native-land.geojson       (~2 MB, WGS84, 5 dp)
#          docs/data/native-land-index.json    (id, slug, name, bbox)
#
# Run from the repo root: Rscript projections-map.R

# install.packages("pak")
packages <- c("sf",
              "dplyr",
              "stringr",
              "stringi",
              "rmapshaper",
              "jsonlite",
              "curl")

if (!all(vapply(packages, requireNamespace, logical(1), quietly = TRUE))) {
  pak::pak(packages, ask = FALSE)
}

library(sf)
library(dplyr)
library(stringr)

BASE <- "https://data.climate.umt.edu/native-climate/projections/"

# Percent-encode a path segment: space -> %20, non-ASCII -> UTF-8 %XX bytes.
# Leaves ' ( ) - . , alone. Byte-identical to JS encodeURI(), and matches the
# URLs the archive server actually resolves. The JS assigns these to a.href
# verbatim and never re-encodes.
url_enc <- function(x) utils::URLencode(enc2utf8(x), reserved = FALSE)

# ── Read ─────────────────────────────────────────────────────────────────────
land <-
  sf::read_sf("native-land.parquet") %>%
  dplyr::transmute(name = as.character(`Native Land`)) %>%
  dplyr::arrange(name) %>%
  sf::st_transform(4326)

# ── Guards ───────────────────────────────────────────────────────────────────
stopifnot(
  "duplicate names" = !anyDuplicated(land$name),
  "invalid geometries" = all(sf::st_is_valid(land)),
  "empty geometries" = !any(sf::st_is_empty(land))
)

# Names currently use only this character set. If a future Census vintage adds
# something new, fail loudly so the URL rule and slug rule get re-checked.
bad_chars <- land$name[!str_detect(land$name, "^[A-Za-z0-9 \\-\u2014,.'\u2018()]+$")]
if (length(bad_chars)) {
  stop("Unexpected characters in names: ", paste(bad_chars, collapse = "; "))
}

# Antimeridian: no feature crosses today (xmin = -174.24). If one ever does,
# split it at the dateline so MapLibre doesn't draw a streak across the world.
bbw <- vapply(sf::st_geometry(land), function(g) {
  b <- sf::st_bbox(g)
  unname(b["xmax"] - b["xmin"])
}, numeric(1))
if (any(bbw > 180)) {
  message("Antimeridian crossers: ", paste(land$name[bbw > 180], collapse = "; "))
  land <-
    sf::st_wrap_dateline(land,
                         options = c("WRAPDATELINE=YES", "DATELINEOFFSET=10"),
                         quiet = TRUE) %>%
    sf::st_make_valid()
}

# ── Attributes ───────────────────────────────────────────────────────────────
land <-
  land %>%
  dplyr::mutate(
    id = dplyr::row_number(),
    # URL-safe, stable key for ?land= deep links (survives row reordering).
    slug = name %>%
      stringi::stri_trans_general("Latin-ASCII") %>%
      tolower() %>%
      str_replace_all("[^a-z0-9]+", "-") %>%
      str_remove_all("^-|-$"),
    # Short map label: "Navajo Nation — Chinle Agency" -> "Chinle Agency";
    # "Hawai‘i Climate Divisions — Kona" -> "Kona". Full name stays in `name`.
    label = dplyr::if_else(str_detect(name, " \u2014 "),
                           str_extract(name, "(?<= \u2014 ).*$"),
                           name),
    pdf_url = paste0(BASE, "pdf/",
                     url_enc(paste0(name, "_CMIP6-climate-projections.pdf"))),
    zip_url = paste0(BASE,
                     url_enc(paste0(str_replace_all(name, " ", "_"), ".zip")))
  )
stopifnot("duplicate slugs" = !anyDuplicated(land$slug))

# ── Simplify ─────────────────────────────────────────────────────────────────
# ~862k vertices -> ~93k. keep_shapes so no small island/village disappears.
simp <- rmapshaper::ms_simplify(land, keep = 0.10, keep_shapes = TRUE)
stopifnot(
  "simplify dropped features" = nrow(simp) == nrow(land),
  "simplify produced invalid geometries" = all(sf::st_is_valid(simp)),
  "simplify produced empty geometries" = !any(sf::st_is_empty(simp))
)

# ── Write GeoJSON ────────────────────────────────────────────────────────────
dir.create("docs/data", showWarnings = FALSE, recursive = TRUE)
geojson_path <- "docs/data/native-land.geojson"
simp %>%
  dplyr::select(id, slug, name, label, pdf_url, zip_url) %>%
  sf::st_write(geojson_path,
               driver = "GeoJSON",
               delete_dsn = file.exists(geojson_path),
               quiet = TRUE,
               layer_options = c("COORDINATE_PRECISION=5",
                                 "RFC7946=YES",
                                 "WRITE_BBOX=NO"))

size_mb <- file.size(geojson_path) / 1e6
message(sprintf("%s: %.2f MB, %d features", geojson_path, size_mb, nrow(simp)))
# If this ever trips, switch the page to PMTiles vector tiles rather than
# shipping a larger GeoJSON.
stopifnot("GeoJSON exceeds 3 MB" = size_mb < 3)

# ── Search index ─────────────────────────────────────────────────────────────
index <-
  simp %>%
  dplyr::mutate(bbox = lapply(sf::st_geometry(simp),
                              function(g) round(as.numeric(sf::st_bbox(g)), 4))) %>%
  sf::st_drop_geometry() %>%
  dplyr::select(id, slug, name, label, pdf_url, zip_url, bbox)

jsonlite::write_json(index,
                     "docs/data/native-land-index.json",
                     auto_unbox = TRUE,
                     digits = NA)
message(sprintf("docs/data/native-land-index.json: %.0f KB",
                file.size("docs/data/native-land-index.json") / 1e3))

# ── Link check (optional) ────────────────────────────────────────────────────
# data.climate.umt.edu resolves to a private IP on campus, so run this from
# off campus: Rscript projections-map.R --check-links
if ("--check-links" %in% commandArgs(trailingOnly = TRUE)) {
  urls <- c(simp$pdf_url, simp$zip_url)
  status <- vapply(urls, function(u) {
    h <- curl::new_handle(nobody = TRUE, followlocation = TRUE)
    tryCatch(curl::curl_fetch_memory(u, h)$status_code, error = function(e) NA_integer_)
  }, integer(1))
  bad <- urls[is.na(status) | status != 200L]
  if (length(bad)) {
    message(length(bad), " URL(s) did not return 200:\n", paste(bad, collapse = "\n"))
  } else {
    message("All ", length(urls), " URLs returned 200.")
  }
}
